# Generated by Django 4.0.3 on 2022-04-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_order_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='medicines',
            field=models.ManyToManyField(through='common.OrderMedicine', to='common.medicine'),
        ),
    ]
